[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stop_loss_vault = "Hc3STUtyD3fQJgZ2qek8GGddY3TRTdtaapwXFFP1gsYj"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
